### PR TITLE
Added bindings for `configure`

### PR DESCRIPTION
**Pull request by leeor**

### CODE REVIEW

**Comment by wyze** [comment]
Thanks for the PR! Could we update the type to support the shape of the object instead of a plain object? Should be just `testIdAttribute` for now.

**Comment by leeor** [comment]
That was actually my first inclination, but the docs use the `testIdAttribute` just as an example, so I wanted to go with a more open approach.

No problem, I'll update the bindings with the shape having only `testIdAttribute` for now.

**Comment by wyze** [comment]
I checked the source code and this is the only config option available currently.

Can the same be done for the `Func` variant and a test to support it? Otherwise, this looks great.

**Comment by leeor** [comment]
You're right, missed that test :-(

Done.

**Pull request merged**
